level_0 = {
    'terrain_forest': '../levels/0/level_0_terrain_forest.csv',
    'terrain_snow': '../levels/0/level_0_terrain_snow.csv',
    'terrain_lava': '../levels/0/level_0_terrain_lava.csv',
    'coins': '../levels/0/level_0_coins.csv',
    'hearts': '../levels/0/level_0_hearts.csv',
    'crates': '../levels/0/level_0_crates.csv',
    'enemies': '../levels/0/level_0_enemies.csv',
    'liquids': '../levels/0/level_0_liquids.csv',
    'ladder': '../levels/0/level_0_ladder.csv',
    'constraints': '../levels/0/level_0_constraints.csv',
    'player': '../levels/0/level_0_player.csv',
    'grass': '../levels/0/level_0_grass.csv',
    'node_pos': (110, 400),
    'unlock': 1,
    'node_graphics': '../graphics/overworld/0'}
level_1 = {
    'terrain_forest': '../levels/1/level_1_terrain_forest.csv',
    'terrain_snow': '../levels/1/level_1_terrain_snow.csv',
    'terrain_lava': '../levels/1/level_1_terrain_lava.csv',
    'coins': '../levels/1/level_1_coins.csv',
    'hearts': '../levels/1/level_1_hearts.csv',
    'fg palms': '../levels/1/level_1_fg_palms.csv',
    'bg palms': '../levels/1/level_1_bg_palms.csv',
    'crates': '../levels/1/level_1_crates.csv',
    'enemies': '../levels/1/level_1_enemies.csv',
    'liquids': '../levels/1/level_1_liquids.csv',
    'ladder': '../levels/1/level_1_ladder.csv',
    'constraints': '../levels/1/level_1_constraints.csv',
    'player': '../levels/1/level_1_player.csv',
    'grass': '../levels/1/level_1_grass.csv',
    'node_pos': (300, 220),
    'node_graphics': '../graphics/overworld/1',
    'unlock': 2}
level_2 = {
    'terrain_forest': '../levels/1/level_1_terrain_forest.csv',
    'terrain_snow': '../levels/1/level_1_terrain_snow.csv',
    'terrain_lava': '../levels/1/level_1_terrain_lava.csv',
    'coins': '../levels/1/level_1_coins.csv',
    'hearts': '../levels/1/level_1_hearts.csv',
    'fg palms': '../levels/1/level_1_fg_palms.csv',
    'bg palms': '../levels/1/level_1_bg_palms.csv',
    'crates': '../levels/1/level_1_crates.csv',
    'enemies': '../levels/1/level_1_enemies.csv',
    'liquids': '../levels/1/level_1_liquids.csv',
    'ladder': '../levels/1/level_1_ladder.csv',
    'constraints': '../levels/1/level_1_constraints.csv',
    'player': '../levels/1/level_1_player.csv',
    'grass': '../levels/1/level_1_grass.csv',
    'node_pos': (480, 610),
    'node_graphics': '../graphics/overworld/2',
    'unlock': 3}
level_3 = {
    'terrain_forest': '../levels/1/level_1_terrain_forest.csv',
    'terrain_snow': '../levels/1/level_1_terrain_snow.csv',
    'terrain_lava': '../levels/1/level_1_terrain_lava.csv',
    'coins': '../levels/1/level_1_coins.csv',
    'hearts': '../levels/1/level_1_hearts.csv',
    'fg palms': '../levels/1/level_1_fg_palms.csv',
    'bg palms': '../levels/1/level_1_bg_palms.csv',
    'crates': '../levels/1/level_1_crates.csv',
    'enemies': '../levels/1/level_1_enemies.csv',
    'liquids': '../levels/1/level_1_liquids.csv',
    'ladder': '../levels/1/level_1_ladder.csv',
    'constraints': '../levels/1/level_1_constraints.csv',
    'player': '../levels/1/level_1_player.csv',
    'grass': '../levels/1/level_1_grass.csv',
    'node_pos': (610, 350),
    'node_graphics': '../graphics/overworld/3',
    'unlock': 4}
level_4 = {
    'terrain_forest': '../levels/1/level_1_terrain_forest.csv',
    'terrain_snow': '../levels/1/level_1_terrain_snow.csv',
    'terrain_lava': '../levels/1/level_1_terrain_lava.csv',
    'coins': '../levels/1/level_1_coins.csv',
    'hearts': '../levels/1/level_1_hearts.csv',
    'fg palms': '../levels/1/level_1_fg_palms.csv',
    'bg palms': '../levels/1/level_1_bg_palms.csv',
    'crates': '../levels/1/level_1_crates.csv',
    'enemies': '../levels/1/level_1_enemies.csv',
    'liquids': '../levels/1/level_1_liquids.csv',
    'ladder': '../levels/1/level_1_ladder.csv',
    'constraints': '../levels/1/level_1_constraints.csv',
    'player': '../levels/1/level_1_player.csv',
    'grass': '../levels/1/level_1_grass.csv',
    'node_pos': (880, 210),
    'node_graphics': '../graphics/overworld/4',
    'unlock': 5}
level_5 = {
    'terrain_forest': '../levels/1/level_1_terrain_forest.csv',
    'terrain_snow': '../levels/1/level_1_terrain_snow.csv',
    'terrain_lava': '../levels/1/level_1_terrain_lava.csv',
    'coins': '../levels/1/level_1_coins.csv',
    'hearts': '../levels/1/level_1_hearts.csv',
    'fg palms': '../levels/1/level_1_fg_palms.csv',
    'bg palms': '../levels/1/level_1_bg_palms.csv',
    'crates': '../levels/1/level_1_crates.csv',
    'enemies': '../levels/1/level_1_enemies.csv',
    'liquids': '../levels/1/level_1_liquids.csv',
    'ladder': '../levels/1/level_1_ladder.csv',
    'constraints': '../levels/1/level_1_constraints.csv',
    'player': '../levels/1/level_1_player.csv',
    'grass': '../levels/1/level_1_grass.csv',
    'node_pos': (1050, 400),
    'node_graphics': '../graphics/overworld/5',
    'unlock': 5}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5}
